name: example_app
description: Example to demo Draggable FAB.
publish_to: none
version: 0.1.4

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  draggable_fab:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2  

flutter:
  uses-material-design: true